version: '3'
services:
  pytuga-ms:
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - DOPPLER_TOKEN=dp.st.dev.xRvs9ilCz3atSeNO7wb2L817owwSFn3CwbZXVr5t
