version: '3'
services:
  pytuga-ms:
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - DOPPLER_TOKEN=<your-doppler-token>
