service: pytuga-ms
provider:
  name: aws
  stackName: pytuga-ms
  runtime: python3.6
  region: us-east-1
  memorySize: 128
  timeout: 30
functions:
  app:
    handler: app.handler
    environment:
      DOPPLER_TOKEN: ${env:DOPPLER_TOKEN}
    events:
      - http: POST /
custom:
  pythonRequirements:
    dockerizePip: non-linux
  customDomain:
    domainName: api.pubnic.com.br
    basePath: 'pytuga'
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateArn: arn:aws:acm:us-east-1:583704988389:certificate/cd492ce3-3010-4572-8b9b-6ebff8126a17
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json
    - yarn.lock
    - start.py
    - Dockerfile
    - docker-compose.yml
    - __pycache__
    - .gitignore
    - .app.log
    - .flake8
    - src/tests/**
    - test.py
plugins:
  - serverless-python-requirements
  - serverless-domain-manager
