service: pytuga-ms
provider:
  name: aws
  stackName: pytuga-ms
  runtime: python3.6
  region: us-east-1
  memorySize: 128
  timeout: 30
functions:
  app:
    handler: app.handler
    environment:
      DOPPLER_TOKEN: ${env:DOPPLER_TOKEN}
    events:
     - alb:
        listenerArn: arn:aws:elasticloadbalancing:us-east-1:583704988389:listener/app/public-load-balancer/c8abde834611a9e2/491953bac048b0cf
        priority: 1
        conditions:
          path: /pytuga
          method:
            - POST
            - OPTIONS
custom:
  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: false
    useStaticCache: false
    invalidateCaches: true
package:
  exclude:
    - .github
    - .vscode
    - node_modules/**
    - .editorconfig
    - config.sh
    - README.md
    - package.json
    - package-lock.json
    - yarn.lock
    - start.py
    - Dockerfile
    - docker-compose.yml
    - __pycache__
    - .gitignore
    - .app.log
    - .flake8
    - src/tests/**
    - test.py
plugins:
  - serverless-python-requirements
