name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install serverless
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: add serverless
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command in frontend directory
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Serverless Deploy
        uses: dhollerbach/github-action-serverless-with-python-requirements@master
        with:
          args: '--stage dev'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
