name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: add serverless
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command in frontend directory
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: deploy:dev # will run `yarn deploy` command in frontend directory
